### ISSUE TITLE
Saidil on HTTPS ja muud turvalisuse normid

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#1]

**Comment by ClevenL** [comment]
Lets Encrypt sertifikaat:
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04
Muud turvanõuded:
http://www.wpbeginner.com/wp-tutorials/9-most-useful-htaccess-tricks-for-wordpress/
