### ISSUE TITLE
Saidil on lahendatud varundamine väljaspool serverit (andmebaas ja failid).

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#14]

**Comment by elleelisa** [comment]
Kasutasime BackupGuardi pluginat ja salvestasin failid endale välisele kõvakettale
![screen shot 2018-01-15 at 22 25 17](https://user-images.githubusercontent.com/22071462/34960369-34c6434a-fa43-11e7-880d-20c3c3584532.png)
![screen shot 2018-01-15 at 22 25 06](https://user-images.githubusercontent.com/22071462/34960370-35632b88-fa43-11e7-8109-e9e41fecf745.png)
