### ISSUE TITLE
Saidil genereeritud sobivad favicon'id.

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#15]

**Comment by ClevenL** [comment]
favicon varastatud siit:
https://www.ardentcreative.com/wp-content/uploads/2013/06/color_web-design-icon-1.png

kasutatud plugin:
Favicon by RealFaviconGenerator

**Comment by ClevenL** [comment]
![qwefqwef](https://user-images.githubusercontent.com/22045387/34963173-cb9113de-fa4f-11e7-926b-fec6ce8acdfd.png)
