### ISSUE TITLE
Saidil on üles ühe lehe või selle osa ulatuses AB testimine.

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#16]

**Comment by elleelisa** [comment]
Kasutasin Nelio A/B Testing pluginat. Alustasin heating experimendiga mis kasutab testimiseks kõige uuemat postitust. 
![screen shot 2018-01-14 at 21 54 20](https://user-images.githubusercontent.com/22071462/34920084-b8701d7a-f975-11e7-904c-46ce99c8fc0f.png)

**Comment by elleelisa** [comment]
![screen shot 2018-01-15 at 23 41 58](https://user-images.githubusercontent.com/22071462/34963176-d092dd40-fa4f-11e7-90ce-bb9f83e442fa.png)

**Comment by elleelisa** [comment]
Kuna Nelio A/B Testing plugin millegipärast ei tööta, otsustasime kasutusele võtta Hotjari (https://www.hotjar.com), et installida oma lehele heatmappi. Protsess oli üllatavalt lihtne ja mugav. Pidi kasutaja tegema, parooli looma, domeeni sisestama ja kopeerima genereeritud koodi headerisse. Kogu protsessi saatis lihtne õpetus. Järgnev pilt näitab klikkide heatmappi.
![27145216_1785309441508690_265647648_o](https://user-images.githubusercontent.com/22071462/35240475-3e19086e-ffbc-11e7-87e3-86125710263d.png)
