### ISSUE TITLE
Saidil on vähemalt ühe sotsiaalvõrgustiku postituse voog.(Twitter, FB)

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#17]

**Comment by elleelisa** [comment]
Kasutasin Facebook Feed WD pluginat ning lisasin lehele DigiTech-i Facebooki postituste voo.
![screen shot 2018-01-14 at 22 12 40](https://user-images.githubusercontent.com/22071462/34920228-11a6e110-f978-11e7-8bd8-9f468c97171b.png)
![screen shot 2018-01-14 at 22 12 25](https://user-images.githubusercontent.com/22071462/34920229-11c2279a-f978-11e7-820e-8dc514c522a6.png)

**Comment by elleelisa** [comment]
![screen shot 2018-01-15 at 23 49 04](https://user-images.githubusercontent.com/22071462/34963197-e8b0b8ca-fa4f-11e7-9659-967667dcfd51.png)
![screen shot 2018-01-15 at 23 48 47](https://user-images.githubusercontent.com/22071462/34963198-e8cae45c-fa4f-11e7-9966-0a3f76495ab1.png)
![Uploading Screen Shot 2018-01-15 at 23.48.38.png…]()
