### ISSUE TITLE
Saab lisada kommentaare, postitusele või e-poel toodetele. Soovitatavalt eraldi lisatud DISQUS vms, mitte sisseehitatud moodul.

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#4]

**Comment by elleelisa** [comment]
Kasutasin DISQUS-i pluginat. Laadisin selle Wordpressi pluginate alt alla. Seejärel tegin Disqus-is kasutaja ja sättisin sealseid sätteid.
![screen shot 2018-01-14 at 18 57 34](https://user-images.githubusercontent.com/22071462/34918815-168dfd14-f962-11e7-8c09-9db53b495229.png)
![screen shot 2018-01-14 at 18 56 05](https://user-images.githubusercontent.com/22071462/34918816-16ad98c2-f962-11e7-8518-49dce96b588a.png)

**Comment by krisr12** [comment]
![screen shot 2018-01-15 at 23 37 41](https://user-images.githubusercontent.com/22071460/34962619-24999cec-fa4d-11e7-9215-b29393f56922.png)

**Comment by elleelisa** [comment]
![screen shot 2018-01-15 at 23 23 45](https://user-images.githubusercontent.com/22071462/34963144-981bf302-fa4f-11e7-9e0a-9aa52f32d0bc.png)
