### ISSUE TITLE
Saidil on galerii. (Ka mobiilsel seadmel toimiv.)

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#8]

**Comment by elleelisa** [comment]
Kasutasin pluginat NextGEN Gallery

**Comment by elleelisa** [comment]
![screen shot 2018-01-15 at 23 29 41](https://user-images.githubusercontent.com/22071462/34963151-ac0eae72-fa4f-11e7-9e61-f88f6f9244b7.png)

**Comment by krisr12** [comment]
![26972373_2351343021558614_1327812913_o](https://user-images.githubusercontent.com/22071460/34963215-0e00a1d0-fa50-11e7-99c1-0dec10e68a5f.jpg)
