### ISSUE TITLE
Saidil erilahendusega ilus ja huvitav Not Found 404 leht!

### ISSUE THREAD

**Issue by krisr12** [krisr12/VeebDev#9]

**Comment by ClevenL** [comment]
Kasutasin seda õpetust:
https://codex.wordpress.org/Creating_an_Error_404_Page
Ascii pärineb siit:
https://www.ascii-code.com/ascii-art/buildings-and-places/fences.php

**Comment by ClevenL** [comment]
![wqef](https://user-images.githubusercontent.com/22045387/34963159-bd346fd4-fa4f-11e7-8a7d-6a6b5ac95d7f.png)
